services:
  app:
    build: ./redis-app
    depends_on:
      - redis

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
