name: Test Project

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests..."

      - name: Test result
        run:  exit 1

  build:
      needs: test
      runs-on: ubuntu-latest

      steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Build project
        run: echo "Building project..."

      - name: Build result
        run: echo "Build successful!"
